name       : network-manager-fortisslvpn
version    : 1.2.10
release    : 10
source     :
    - https://download.gnome.org/sources/NetworkManager-fortisslvpn/1.2/NetworkManager-fortisslvpn-1.2.10.tar.xz : 7a642a1c33ff71cca578d3135cd7ea686a190b2ba9b27025233612fd3a3386eb
license    : GPL-2.0-or-later
component  : network.util
summary    : Fortinet SSLVPN support for NetworkManager
description: |
    Support for the Fortinet SSLVPN in the NetworkManager.
rundeps    :
    - openfortivpn
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnma)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsecret-unstable)
    - ppp-devel
setup      : |
    %configure --disable-static --with-pppd-plugin-dir=%libdir%/pppd/2.4.8/
build      : |
    %make
install    : |
    %make_install
