name       : network-manager-fortisslvpn
version    : 1.4.0
release    : 17
source     :
    - https://download.gnome.org/sources/NetworkManager-fortisslvpn/1.4/NetworkManager-fortisslvpn-1.4.0.tar.xz : b055e26349b516b23585798ab3ef57b436b014800e92a8ac732cfc8e76c5dafa
license    : GPL-2.0-or-later
component  : network.util
summary    : Fortinet SSLVPN support for NetworkManager
description: |
    Support for the Fortinet SSLVPN in the NetworkManager.
rundeps    :
    - openfortivpn
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk4)
    - pkgconfig(libnma)
    - pkgconfig(libsecret-1)
    - ppp-devel
setup      : |
    # Only dbus-1 goes into sysconfdir (etc by default) so move it
    %configure --disable-static --sysconfdir=/usr/share --with-pppd-plugin-dir=%libdir%/pppd/2.4.8/ --with-gtk4
build      : |
    %make
install    : |
    %make_install
