name       : network-manager-fortisslvpn
version    : 1.2.4
release    : 1
source     :
    - https://git.gnome.org/browse/network-manager-fortisslvpn/snapshot/network-manager-fortisslvpn-1.2.4.tar.xz : e0478cf4418f0dc8923f4edaaf35d946f3b7b02489da8f96e0f24cfaae4f9252
license    : GPL-2.0
component  : network.util
summary    : Fortinet SSLVPN support for NetworkManager
description: |
    Support for the Fortinet SSLVPN in the NetworkManager.
rundeps :
    - openfortivpn
builddeps  :
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnma)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(libnm-gtk)
    - pkgconfig(libnm)
    - ppp-devel
    - pkgconfig(dbus-glib-1)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
