name       : network-manager-fortisslvpn
version    : 1.2.8
release    : 7
source     :
    - https://download.gnome.org/sources/NetworkManager-fortisslvpn/1.2/NetworkManager-fortisslvpn-1.2.8.tar.xz : 9cb8e5df0bc0ecc2ab4bfbf022df463bfc1ea01c06617a0be87fdbd9d26efb05
license    : GPL-2.0
component  : network.util
summary    : Fortinet SSLVPN support for NetworkManager
description: |
    Support for the Fortinet SSLVPN in the NetworkManager.
rundeps    :
    - openfortivpn
builddeps  :
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnma)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(libnm-gtk)
    - pkgconfig(libnm)
    - ppp-devel
    - pkgconfig(dbus-glib-1)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
